version: '3'
services:
  db:
    image: mysql:8.0
    networks:
      - my-pet-project-network
    container_name: mysqlPetProject
    ports:
      - 4000:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: testDB
    volumes:
      - db_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:management
    networks:
      - my-pet-project-network
    container_name: rabbitmq
    ports:
      - "5672:5672" # порт для AMQP протокола
      - "15672:15672" # порт для веб-интерфейса RabbitMQ
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest # логин по умолчанию
      - RABBITMQ_DEFAULT_PASS=guest # пароль по умолчанию
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    networks:
      - my-pet-project-network
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    networks:
      - my-pet-project-network
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.0.108:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  prometheus:
    image: prom/prometheus:latest
    networks:
      - my-pet-project-network
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - ./prometheus:/prometheus
    ports:
    - "19090:9090"

  grafana:
    build: './scripts/config/grafana'
    networks:
      - my-pet-project-network
    ports:
    - "13000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_AMIND_PASSWORD=admin
    volumes:
    - grafana-data:/var/lib/grafana

volumes:
  rabbitmq_data:
    driver: local
  db_data:
    driver: local
  grafana-data:

networks:
  my-pet-project-network:
    driver: bridge
