version: '3'
services:
  db:
    image: mysql:8.0
    container_name: mysqlPetProject
    ports:
      - 4000:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: testDB
#    volumes:
#      - ./data:/var/lib/mysql
    restart: always
#  spring-boot-app:
#    image: spring-boot-app:test
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/testDB?autoReconnect=true&useSSL=false
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#    build:
#      context: "./"
#      dockerfile: "Dockerfile"
#    depends_on:
#      - db