name: My GitHub Action

on:
  push:
    branches:
      - master
      - uat
  pull_request:
    branches:
      - master
      - uat

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean install


      - name: Build and Push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: mekcc/PetProject
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
